name: Sync to Gitee

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        run: |
          git remote add gitee https://wang-zini:${{ secrets.GITEE_TOKEN }}@gitee.com/wang-zini/ClassBridge.git
          git push -f gitee main:main
