name: Sync to Gitee

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github repo to Gitee
        uses: Yikun/gitee-pipeline-action@v1.2
        with:
          gitee-user: 'wang-zini'
          gitee-repo: 'ClassBridge'
          gitee-token: ${{ secrets.GITEE_TOKEN }}
          result-item-count: '1'
